import { DM_Sans, Playfair_Display } from "next/font/google";

import "./globals.css";

import NavBar from "@/components/navBar";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--playfair-display",
});
const dm_sans = DM_Sans({
  subsets: ["latin"],
  variable: "--dm-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${playfair.variable} ${dm_sans.variable}`}>
      <body>
        <NavBar />

        {children}
      </body>
    </html>
  );
}
